# Generated by Django 2.0.5 on 2018-05-22 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CallDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_call', models.CharField(choices=[('start', 'Start'), ('end', 'End')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phone.Call')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='phone.Phone'),
        ),
        migrations.AddField(
            model_name='call',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='phone.Phone'),
        ),
    ]
