# Generated by Django 2.0.5 on 2018-05-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_start_date', models.DateTimeField()),
                ('call_start_time', models.TimeField()),
                ('call_duration', models.TimeField()),
                ('call_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phone.Call')),
            ],
        ),
    ]
