# Generated by Django 2.0.5 on 2018-05-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcall',
            name='call_duration',
            field=models.DurationField(),
        ),
    ]
