# Generated by Django 2.0.5 on 2018-05-29 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_auto_20180528_2345'),
        ('bill', '0003_auto_20180527_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billcall',
            name='call',
        ),
        migrations.AddField(
            model_name='billcall',
            name='call_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='phone.Call'),
            preserve_default=False,
        ),
    ]
